version: '3.4'

services:

  categorymsapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - 'DB_URL=jdbc:postgresql://DBALB-1b4244899839faea.elb.us-east-1.amazonaws.com:5432/categoryms?ApplicationName=categoryMicroService'
      - 'DB_HOST=DBALB-1b4244899839faea.elb.us-east-1.amazonaws.com'
      - 'DB_PORT=5432'
      - 'DB_NAME=categoryms'
      - 'DB_USER=admin'
      - 'DB_PASS=passwOrd'
